### ISSUE TITLE
[Bug] Problem xxx

### ISSUE THREAD

**Issue by psycholali** [EcjtuNet/hr_ecjtu_net#3]
## please complete the following information（请提供以下信息，包括系统、浏览器、nohost、node版本）:
 - Node Version [e.g. 14.4.0]

**Comment by superkevingit** [comment]
咦～

**Comment by pr1mavera** [comment]
喵 ？

Zikai Zhang ***@***.***> 于2021年4月20日周二 上午11:31写道：

**Comment by psycholali** [comment]
试用一下issue template 哈哈哈哈 我等会删掉

发自我的iPhone

**Comment by superkevingit** [comment]
什么是快乐星球
